#server:
#  port: 8081
#
#spring:
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
#    - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
#  application:
#    name: smsapi-all
#  profiles:
#    active:
#      - test3
#  cloud:
#    vault:
##      token: s.61nDRiaeDD5ojuQuBTATKdYR
#      token: ${VAULT_TOKEN:s.7eX56ayfSGsJdGxjsOLVFKBr}
#      authentication: token
#      port: 8200
#      scheme: https
#      host: vault.omtools.me
#      kv:
#        enabled: true
#
#
#
#
